title: Predicting Transit Demand for the Chicago ‘L’ Using Random Forest
logo: /assets/img/logo.png
description: Saiya Sheth & Tiffany M. Tran
show_downloads: false
repository: tfmtran/chicago-transit
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
